version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "alertmanager-to-typetalk"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rd8bg632k1el"
s3_prefix = "alertmanager-to-typetalk"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

