AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Webhook for transferring notification from Alertmanager to Typetalk

Globals:
  Function:
    Timeout: 3

Resources:
  AlertManagerToTypetalkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          DEBUG: true
      Events:
        AlertManagerToTypetalkEvent:
          Type: Api
          Properties:
            Path: /{topicId}
            Method: post

Outputs:
  AlertManagerToTypetalkApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AlertManagerToTypetalkFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AlertManagerToTypetalkFunction.Arn
  AlertManagerToTypetalkFunctionIamRole:
    Description: "Implicit IAM Role created"
    Value: !GetAtt AlertManagerToTypetalkFunctionRole.Arn
